source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

def thepods
    pod 'MindV', :git => 'https://github.com/pakidanish/MindV.git', :tag => '1.0.11'
end

target "NineNews" do
    thepods
end